---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.16
        # env:
        # - name: VAULT_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       key: samplekey
        #       name: static-secret
        # envFrom:
        # - configMapRef:
        #     name: proxy-env
